acon.syntax = $__config__/acon.syntax
atop.conf = $__config__/atop.conf
cobf_algorithms.cobf = $__config__/cobf_algorithms.cobf
dynap_exclude.scfg = $__config__/dynap_exclude.scfg
dynav_ignore.lst = $__config__/dynav_ignore.lst
openf.conf = $__config__/openf.conf
shgest.conf = $__config__/shgest.conf
startup.conf = $__config__/startup.conf
llsi.init = $__init__/llsi.init