history = true
history_color = \x1b[38;5;245m

alias = true
alias_color = \x1b[38;5;202m

function = true
function_color = \x1b[1m\x1b[38;2;110;90;180m

builtin = true
builtin_color = \x1b[0;34m

tool = true
tool_color = \x1b[0;32m

variable = true
variable_color = \x1b[0;31m

path = true
path_color = \x1b[1m\x1b[38;2;0;110;185m

cutter_symbol = ...
cutter_color = \x1b[1;31m

other_color = \x1b[38;5;245m