home = ~
toolkit = $__aresroot__/bin, <+readonly>
chmod_toolkit = true
remove_log = false
remove_binext = true
remove_gscache = false
remove_cscache = false # coming soon
startup_hint = true
cursor = blink-underline
prompt = true
prompt_engine = yumipr
yumipr_theme = themes/default.lua
suggestion = false
suggestion_engine = shgest
cnf = true
cnf_engine = cnf_handler
lock_variable = true